/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 low_poly_assets.glb --types, -t 
Author: premudraya (https://sketchfab.com/premudraya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-assets-c5f2e7eacc0f4e659c4188925fcb84f1
Title: Low poly assets
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshBasicMaterial
    ['Material.002']: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/low_poly_assets.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[5.321, 5.606, -6.534]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.999} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[-7.151, 9.743, -5.614]} rotation={[0, -0.569, 0]} scale={0.999} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} position={[-21.983, 9.743, -5.614]} rotation={[0, -0.569, 0]} scale={0.999} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[-35.744, 6.686, -4.695]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.999} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} position={[-9.24, 5.07, -26.05]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.641} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} position={[-22.965, 5.07, -13.16]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.641} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} position={[5.194, 4.074, -16.837]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.716} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.001']} position={[-9.541, 8.793, -16.831]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.959} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.001']} position={[-35.857, 4.868, -13.452]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.826} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.001']} position={[-49.78, 9.236, -5.587]} rotation={[0, -0.569, 0]} scale={0.999} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.001']} position={[-50.629, 4.749, -13.159]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.641} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.001']} position={[-64.714, 9.236, -5.587]} rotation={[0, -0.569, 0]} scale={0.999} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.001']} position={[-65.578, 4.749, -13.159]} rotation={[-Math.PI, 0.569, -Math.PI]} scale={0.641} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.001']} position={[27.049, -0.154, -3.625]} rotation={[0, -0.569, 0]} scale={0.49} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.001']} position={[32.523, -0.187, -3.643]} rotation={[0, -0.569, 0]} scale={0.49} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.001']} position={[37.689, -0.875, -0.377]} rotation={[0, 1.474, 0]} scale={0.333} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.001']} position={[39.139, 0.536, -3.497]} rotation={[-1.063, 0.062, 0.28]} scale={0.236} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.001']} position={[44.749, 0.536, -3.497]} rotation={[-1.063, 0.062, 0.28]} scale={0.236} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.001']} position={[40.295, -1.035, -0.279]} rotation={[0, 1.474, 0]} scale={0.333} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Material.001']} position={[43.467, -0.875, -0.377]} rotation={[0, 1.474, 0]} scale={0.333} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Material.001']} position={[45.868, -1.035, -0.279]} rotation={[0, 1.474, 0]} scale={0.333} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Material.001']} position={[27.049, 0.068, -8.784]} rotation={[0, -0.569, 0]} scale={0.49} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['Material.001']} position={[27.049, 0.868, -12.789]} rotation={[0, -0.569, 0]} scale={0.49} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Material.001']} position={[32.486, -1.232, -8.4]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Material.001']} position={[32.487, -1.211, -12.774]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['Material.001']} position={[32.485, -1.375, -16.446]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Material.001']} position={[32.487, -1.25, -20.248]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials['Material.001']} position={[16.059, 0.86, -4.881]} scale={[2.478, 0.111, 0.111]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['Material.001']} position={[39.045, 1.458, -8.522]} rotation={[0, -0.569, 0]} scale={0.49} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['Material.001']} position={[16.059, 0.86, -11.188]} scale={[2.478, 0.111, 0.111]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Material.001']} position={[16.135, 8.411, -14.66]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['Material.001']} position={[16.031, 7.94, -21.468]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Material.001']} position={[22.421, 8.534, -15.231]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Material.001']} position={[22.182, 8.187, -20.318]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials['Material.001']} position={[22.422, 0.968, -10.45]} scale={[0.182, 3.273, 0.182]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['Material.001']} position={[22.422, -0.096, -4.655]} scale={[0.175, 3.151, 0.175]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['Material.001']} position={[22.442, 5.948, -24.079]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials['Material.001']} position={[22.073, 5.614, -28.252]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials['Material.001']} position={[42.437, 0.392, -25.89]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials['Material.001']} position={[42.645, 0.543, -22.813]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['Material.001']} position={[30.502, 0.324, -26.19]} scale={[0.185, 1.097, 0.185]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials['Material.001']} position={[35.745, 0.356, -26.19]} scale={[0.185, 1.097, 0.185]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials['Material.001']} position={[30.477, 0.316, -23.303]} scale={[0.185, 1.097, 0.185]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials['Material.001']} position={[35.647, 0.281, -23.303]} scale={[0.185, 1.097, 0.185]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials['Material.001']} position={[25.252, 7.947, -34.154]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials['Material.002']} position={[25.241, 8.482, -33.796]} scale={[1.637, 1.637, 0.165]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['Material.001']} position={[20.853, 7.765, -34.171]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['Material.002']} position={[20.885, 7.99, -33.67]} scale={[2.126, 1.992, 1.992]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials['Material.001']} position={[15.833, 7.925, -34.047]} scale={[0.31, 5.576, 0.31]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['Material.002']} position={[15.827, 8.355, -33.604]} rotation={[Math.PI / 2, 0, 0]} scale={1.942} />
    </group>
  )
}

useGLTF.preload('/low_poly_assets.glb')
